site_name: Authoritah Wiki

repo_url: https://github.com/NX211/authoritah-wiki/

theme:
  name: material
  custom_dir: overrides
  logo: images/logo.png
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - search:
      lang: en

markdown_extensions:
  - abbr
  - admonition # enables coloured blocks mid article
  - attr_list # improves image handling
  - pymdownx.details # enables collapsible admonitions
  - footnotes
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.highlight: # code highlighting
      linenums: true
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences # allows for the nesting of code blocks inside other blocks
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2023 <a href="https://www.authoritah.com"  target="_blank" rel="noopener">Authoritah.com</a>

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/NX211/authoritah-wiki/'
      name: Authoritah Wiki on GitHub
  analytics:
    provider: plausible
    property: authoritahwiki
  generator: false

nav:
  - Home: index.md
  - Services: services/index.md
  - Hardware: hardware/index.md
  - Network: network/index.md
